name: validate-query-results-example

on:
  schedule:
    - cron: "0 0 1 * *"
env:
  working-directory: bigquery_validator/tests
jobs:
  run_bigquery_result_baseball_test:
    runs-on: ubuntu-latest
    env:
      working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: |
          python -m pip install --upgrade pip
          pip install -r ./tests/requirements.txt
      - name: Check that SQL query returns expected data
        working-directory: ${{ env.working-directory }}
        run: |
          pytest baseball_data_validation_test.py 
