# This workflow will install dependencies, create coverage tests and run Pytest Coverage Commentator
# For more information see: https://github.com/coroo/pytest-coverage-commentator
name: pytest-coverage-commentator
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#    - name: Build coverage file
#      run: |
#        pytest --cov=pubsub_to_bq tests --cov-fail-under=80
#    # - name: Add changed files
#    #   run: git add .
#    # - name: Commit file
#    #   run: git commit -m "Adding Pytest file for <commit hash>"
#    - name: Comment coverage
#      uses: coroo/pytest-coverage-commentator@v1.0.2
    - name: Run unit tests
      run: |
        cd bigquery_validator
        pytest bigquery_validator_test.py
