name: run-bigquery-result-unit-tests
on:
  push
jobs:
  bigquery-result-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest coverage
    - name: Run unit tests
      run: |
        cd bigquery_validator/tests
        pytest bigquery_result_test.py
    # - name: Check test coverage
    #   run: |
    #     cd bigquery_validator/tests
    #     coverage run -m pytest tests/bigquery_result_test.py
    #     coverage report -m
    #     coverage json --fail-under=80
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies for Python 3.12
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Run unit tests on Python 3.12
      run: |
        cd bigquery_validator/tests
        pytest bigquery_result_test.py
